version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t4w6r5w9
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - pwd
      - ls -al
      - echo ${IMAGE_TAG}
  build:
    commands:
      - pwd
      - ls -al
      - docker images
      - docker build -t app:latest .
      - docker tag elogin:latest public.ecr.aws/t4w6r5w9/elogin:$IMAGE_TAG
  post_build:
    commands:
      - docker push public.ecr.aws/t4w6r5w9/elogin:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"elogin","imageUri":"%s"}]' public.ecr.aws/t4w6r5w9/elogin:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json


