"DbUser" = "postgres"
"DbPassword" = "123456"
"DbName" = "TechChallengeApp"
"DbPort" = "3306"
"DbHost" = "techchallengeapp.crpuz1awsieu.ap-southeast-2.rds.amazonaws.com"
"ListenHost" = "13.54.224.225"
"ListenPort" = "3000"